import{A as h,i as c,S as m}from"./assets/vendor-BbbysJIu.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const f=document.querySelectorAll(".marquee");f.forEach(e=>{e.innerHTML+=e.innerHTML});const g=[{info:"What programming language are most often used in your project?",more:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{info:"What are the deadlines for the project?",more:"The terms of project implementation depend to a large extent on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines is a difficult task, and it usually occurs during the planning phase of the project."},{info:"What payment methods do you accept?",more:"Payment through credit and debit cards such as Visa, MasterCard, specialized electronic payment systems such as PayPal, as well as payments in cryptocurrencies such as Bitcoin, Ethereum and others."},{info:"How can I contact you?",more:"In the field of web development, there are various technologies and programming languages. Typically, this includes a combination of frontend (client side) and backend (server side) languages."},{info:"Do you provide advice or support?",more:"The terms of project implementation depend to a large extent on a number of factors, such as the scope of the project, its complexity, and the availability of resources. Determining exact deadlines is a difficult task, and it usually occurs during the planning phase of the project."},{info:"What does the process of developing a software product look like from idea to implementation?",more:"Payment through credit and debit cards such as Visa, MasterCard, specialized electronic payment systems such as PayPal, as well as payments in cryptocurrencies such as Bitcoin, Ethereum and others."}],y={duration:300,showMultiple:!1,openOnInit:[0]},v=e=>`
  <li class="ac">
    <h2 class="ac-header">
      <button class="ac-trigger" type="button">
        ${e.info}
        <span class="arrow" aria-hidden="true"></span>
      </button>
    </h2>
    <div class="ac-panel">
      <p class="ac-text">${e.more}</p>
    </div>
  </li>
`,w=e=>{const o=e.target.closest(".ac-trigger");if(!o)return;const n=o.closest(".ac"),s=n.querySelector(".ac-panel"),t=o.querySelector(".arrow"),r=n.classList.contains("is-active");document.querySelectorAll(".ac-panel").forEach(a=>{a.style.height="0",a.setAttribute("aria-expanded","false")}),document.querySelectorAll(".arrow").forEach(a=>a.classList.remove("rotate")),r||(s.style.height=`${s.scrollHeight}px`,s.setAttribute("aria-expanded","true"),t.classList.add("rotate"))},l=()=>{const e=document.querySelector(".accordion-container");if(!e){console.warn("FAQ container not found");return}try{e.innerHTML=g.map(v).join(""),new h(".accordion-container",y),e.addEventListener("click",w),document.querySelectorAll(".ac-panel").forEach((o,n)=>{o.setAttribute("aria-expanded",n===0?"true":"false")})}catch(o){console.error("Error initializing FAQ:",o)}};document.readyState==="loading"?document.addEventListener("DOMContentLoaded",l):l();const b=document.querySelector(".reviews-list-js"),d=document.querySelector(".reviews-placeholder-js"),u=document.querySelector(".prev-btn-js"),p=document.querySelector(".next-btn-js"),L="https://portfolio-js.b.goit.study/api/reviews";fetch(L).then(e=>{if(!e.ok)throw new Error("Failed to load reviews");return e.json()}).then(e=>{if(!e.length){d.classList.remove("visually-hidden");return}const o=e.map(({avatar_url:n,author:s,review:t})=>`
        <li class="swiper-slide review-item">
          <p class="review-text">${t}</p>
          <div class="author-info">
          <img class="author-img" src=${n} alt="${s}"
          <p style="bold" class="reviewer-name">${s}</p>
          </div>
        </li>`).join("");b.innerHTML=o,j()}).catch(()=>{c.error({message:"Failed to load reviews",position:"topRight"}),d.classList.remove("visually-hidden")});function j(){new m(".reviews-slider-js",{slidesPerView:1,spaceBetween:16,loop:!1,autoHeight:!0,navigation:{prevEl:".prev-btn-js",nextEl:".next-btn-js"},keyboard:{enabled:!0},on:{reachBeginning(){u.disabled=!0},fromEdge(){u.disabled=!1,p.disabled=!1},reachEnd(){p.disabled=!0}}})}const i=document.querySelector("#contactForm");i.addEventListener("submit",async e=>{e.preventDefault();const o=new FormData(i);try{if(!(await fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",body:o})).ok)throw new Error("Something went wrong when submitting the application.");c.success({title:"Thank you for your interest in cooperation!",message:"The manager will contact you shortly to discuss further details and opportunities for cooperation. Please stay in touch.",position:"center"}),i.reset()}catch(n){c.error({title:"Помилка",message:n.message||"An error occurred. Try again!",position:"center"})}});
//# sourceMappingURL=index.js.map
